@startuml
class Client {
    + Client()
    + Client(id:string, name:string, surname:string, userName:string, direccionFacturacion:string)
    + DireccionFacturacion : string? <<get>> <<set>>
}
class "IList`1"<T> {
}
ApplicationUser <|-- Client
Client o-> "ComprasAccesorios<CompraAccesorios>" "IList`1"
@enduml
