@startuml
!include .\\ApplicationUser.puml
!include .\\Client.puml
!include .\\MetodoPago.puml
!include .\\UC_Reservar\Impresora3D.puml
!include .\\UC_Reservar\LineaReserva.puml
!include .\\UC_Reservar\ReservaImpresora.puml
!include .\\UC_Reservar\TiempoReserva.puml
!include .\\UC_Reservar\TipoImpresora.puml
@enduml
