@startuml
class ReservaImpresora {
    + ReservaImpresora()
    + ReservaImpresora(fechaReserva:DateTime, nombreCliente:string, apellidosCliente:string, direccionFacturacion:string, precioTotal:decimal, metodoPago:MetodoPago, client:Client)
    + Id : int <<get>> <<set>>
    + FechaReserva : DateTime <<get>> <<set>>
    + NombreCliente : string <<get>> <<set>>
    + ApellidosCliente : string <<get>> <<set>>
    + DireccionFacturacion : string <<get>> <<set>>
    + PrecioTotal : decimal <<get>> <<set>>
    + MetodoPago : MetodoPago <<get>> <<set>>
    + ClienteId : string <<get>> <<set>>
    + <<virtual>> Cliente : Client <<get>> <<set>>
    + <<virtual>> LineasReserva : ICollection<LineaReserva> <<get>> <<set>>
}
@enduml
