@startuml
class LineaCompraAccesorio {
    + LineaCompraAccesorio()
    + LineaCompraAccesorio(cantidad:int, precioUnidad:decimal)
    + Id : int <<get>> <<set>>
    + Cantidad : int <<get>> <<set>>
    + PrecioUnidad : decimal <<get>> <<set>>
    + Subtotal : decimal <<get>>
}
LineaCompraAccesorio o-> "CompraAccesorios" CompraAccesorios
LineaCompraAccesorio o-> "Accesorio" Accesorio
@enduml
